The Restaurant App
acushlakoncept/restaurant-page pull request #1
Opened 2020-09-15 18:26 UTC by acushlakoncept

This PR contains the full implementation of a Simple Restuarant Page App using webpack. DOM manipulation was also implemented to dynamically render the various pages: Home, Menu, and Contact.

2020-09-15 23:58 UTC, mikenath223 requested changes
### Hi @acushlakoncept  👋

**You've done quite well with this project.👍**

However, let's make some changes and we would be good to go.

### **Please refer to the comments made on your code below**

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-09-16 00:00 UTC, mikenath223 commented on dist/index.html
> +    </div>
- [ ] You are expected to make index.html very lean. Pleas remove this nav element and dynamically create it with JavaScript instead.

2020-09-16 00:02 UTC, mikenath223 commented on dist/index.html
> +    ></script>
- [ ] Also please remove this script and its contents and refer to [this link](https://getbootstrap.com/docs/4.0/getting-started/webpack/) for instructions on how to use bootstrap with webpack.

2020-09-16 00:08 UTC, mikenath223 commented on package.json
> +    "eslint": "^6.8.0",
- [ ] Please add necessary run common commands like build, development and start in package.json inside `scripts'.

2020-09-16 22:18 UTC, Dandush03 approved these changes
# Status: :rocket: Approved :rocket: :smile: 
# Keep it up
# :computer: Happy Coding :computer:

2020-09-17 04:37 UTC, merged